#!/usr/bin/env python3

from os import environ, sep
from pathlib import Path, PurePath
from subprocess import check_call, run

check_call(
    (
        PurePath(sep) / "command" / "s6-svwait",
        "-U",
        Path.cwd().parent / "broadwayd",
    )
)

# Attendre que le socket libvirt soit créé par le service libvirtd
sock = Path(sep) / "var" / "run" / "libvirt" / "libvirt-sock"
while not sock.exists():
    import time

    time.sleep(1)

while True:
    run(
        (
            PurePath(sep) / "bin" / "dbus-run-session",
            "--",
            PurePath(sep) / "bin" / "virt-manager",
            "--no-fork",
            "--connect",
            environ["VIRT_CONN"],
        )
    )
