#!/usr/bin/env python3

from os import sep
from pathlib import PurePath
from subprocess import call
from time import sleep

while call(
    (
        PurePath(sep) / "bin" / "curl",
        "--silent",
        "--fail",
        "--max-time",
        "2",
        "http://127.0.0.1:8080",
    )
):
    sleep(1)
